name: TSC
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          cache: "yarn"
      - run: yarn install
      - run: cd example && yarn install && cd ..
      - run: yarn run check
